### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by aintgoin2goa** [Financial-Times/next-mission-control#10]
- [ ] Custom metrics per-app
- [ ] Custom actions per-app
- [ ] Manual region failover
- [ ] Figure out load thresholds
- [ ] Get uptime data from pingdom
- [ ] Get health data from wherever we monitor that
- [ ] Metrics and actions for non-heroku apps (fastly, aws)
- [ ] Get heroku metrics into graphite and use that as single authority
- [ ] Persist scaling by saving to registry somehow
